version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@5.0.3
  heroku: circleci/heroku@2.0.0
  browser-tools: circleci/browser-tools@1.4.1

commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Precompile assets
          command: bundle exec rails assets:precompile

jobs:
  rubocop:
    docker:
      - image: cimg/ruby:3.0.5-node
    working_directory: ~/bandapp
    steps:
      - setup
      - ruby/rubocop-check

  rspec:
    docker:
      - image: cimg/ruby:3.0.5-node
        environment:
          RAILS_ENV: test
          APP_DATABASE_HOST: "127.0.0.1"
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ci_test
    working_directory: ~/bandapp
    steps:
      - setup
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: mv config/database.ci.yml config/database.yml
      - run:
          name: rails db:create
          command: bundle exec rails db:create
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - ruby/rspec-test

  heroku_deploy:
    docker:
      - image: cimg/ruby:3.0.5-node
    working_directory: ~/bandapp
    steps:
      - setup
      - heroku/install
      - run:
          name: Set Heroku-20 stack
          command: heroku stack:set heroku-20 -a $HEROKU_APP_NAME
      - heroku/deploy-via-git
      - run:
          name: Post Deploy
          command: heroku run rails db:migrate -a $HEROKU_APP_NAME

workflows:
  version: 2.1
  build:
    jobs:
      - rubocop
      - rspec
      - heroku_deploy:
          requires:
            - rubocop
            - rspec
